apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccountName }}
      initContainers:
        - name: secret-mounter
          image: busybox
          command: ["sleep", "20"]
          volumeMounts:
            - name: secrets
              mountPath: /mnt/secrets
        
      containers:
        - name: {{ .Values.controller.containerName }}
          image: {{ .Values.controller.image }}
          ports:
            - containerPort: {{ .Values.controller.port }}
          {{- if .Values.controller.env }}
          env:
            {{- toYaml .Values.controller.env | nindent 12 }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          
          livenessProbe:
            {{- toYaml .Values.controller.livenessProbe | nindent 12 }}
          
          readinessProbe:
            {{- toYaml .Values.controller.readinessProbe | nindent 12 }}
      
      {{- if .Values.controller.affinity }}
      affinity:
        {{- toYaml .Values.controller.affinity | nindent 8 }}
      {{- end }}
      
      volumes:
        {{- toYaml .Values.controller.volumes | nindent 8 }}