apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- .Values.controller.serviceAccountName .}}
  namespace: back-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    eks.amazonaws.com/role-arn: {{- .Values.controller.secretsManagerRoleArn | quote }}
  