{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: back-ns
spec:
  podSelector:
    matchLabels:
      app: {{- include "backend.selectorLabels" }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: front-ns
          podSelector:
            matchLabels:
              {{- include "frontend.selectorLabels" }}
      ports:
        - protocol: TCP
          port: {{- .Values.controller.port . }}
