apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: db-secrets
  namespace: back-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "iti_gp_db_secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
