apiVersion: apps/v1
kind: Deployment

metadata:
  name: front-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
{{- include "frontend.selectorLabels" .  | nindent 6}}
  template:
    metadata:
      name: front-pod
      labels:
{{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
              subPath: proxy.conf

        - name: front-container
          image: {{ .Values.controller.image }}
          ports:
            - containerPort: {{ .Values.controller.port }}
{{- if .Values.controller.env }}
          env:
{{- toYaml .Values.controller.env | nindent 12 }}
{{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: back-service-name-cm
      