apiVersion: v1
kind: Service

metadata:
  name: front-service
  namespace: front-ns
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations . }}
  {{- end }}

spec:
  selector:
    {{- include "frontend.selectorLabels" }}
  type: {{- .Values.service.type }}
  ports:
    {{- .Values.service.ports . }}
