apiVersion: v1
kind: Service

metadata:
  name: front-service
  namespace: front-ns
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}

spec:
  selector:
    {{- include "frontend.selectorLabels" }}
  type: {{- .Values.service.type }}
  ports:
  ports:
{{- toYaml .Values.service.ports | nindent 4 }}

