backend:
  host: back-service.back-ns.svc.cluster.local
  port: 5000

controller:
  port: 3000
  replicaCount: 3
  image: bstar999/iti-gp-image-front:latest

  env:
    - name: REACT_APP_API_URL
      value: "http://back-service.back-ns.svc.cluster.local:5000/api"


service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    #service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0708835103d04ffed,subnet-08f42402182b2703b"
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Pod port