apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
  namespace: db-ns
spec:
  capacity:
    storage: {{ .Values.persistence.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: ""        # Empty for static binding 
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
    type: {{ .Values.persistence.hostPath.type }}