apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-secret-sa
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    eks.amazonaws.com/role-arn: arn:aws:iam::910148268074:role/db_secret_role