apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend
  namespace: db-ns
spec:
  podSelector:
    matchLabels:
      {{- include "db.network.backendLabels" . | nindent 6}}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "db.network.backendLabels" . | nindent 10}}
    ports:
    - protocol: TCP
      port: {{ .Values.controller.containerPort }}